name: audacious gtk build

on:
  push:
    paths:
      - '.github/workflows/build.yml' 

jobs:
  debian-container:
    runs-on: ubuntu-latest
    container: debian:stable
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: clone audacious repo
        run: |
              apt-get update && apt-get install -y  gcc autoconf automake gettext libtool cmake pkg-config  libgtk-3-dev  git locales g++ zip
              git clone --branch master-gtk3 https://github.com/audacious-media-player/audacious.git --depth=1
              cd audacious
              ./autogen.sh
               pw=$(realpath .)
              mkdir $pw/pkg
              ./configure --disable-qt --enable-gtk  
              make
              make install
              ./configure --disable-qt --enable-gtk --prefix=$pw/pkg
              make install
              zip -r aud.zip pkg/
              
              # building plugins need audacious installed so two configure
              
              cd ..
              sudo apt install -y libxml2-dev libflac-dev libvorbis-dev libogg-dev libmpg123-dev libwavpack-dev libavcodec-dev libavformat-dev libavutil-dev libpipewire-0.3-dev libspa-0.2-dev libneon27-dev
              git clone --branch master-gtk3 https://github.com/audacious-media-player/audacious-plugins.git --depth=1
              cd audacious-plugins
              pww=$(realpath .)
              mkdir $pww/pkg
              ./configure --disable-qt --enable-gtk  --prefix=$pw/pkg
              make
              make install
              zip -r aud-plugins.zip pkg/
              
              
              
        
      - name: Create GitHub Release and Upload ZIP
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.run_id }}
          files: |
            ${{ github.workspace }}/audacious/aud.zip
            ${{ github.workspace }}/audacious-plugins/aud-plugins.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
